# Makefile (this is -*- Makefile -*-)
# 
# This is a makefile skeleton. In a lot of projects, this doesn't have
# to be modified at all. If you do have to or want to modify it,
# please let the comments guide you.
# 
#    Last Author: !!userinfo-fullname!! (<!!userinfo-email!!>)
#    Date of last change:  !!actual-date!!
#
#    Author:    !!userinfo-fullname!! (<!!userinfo-email!!>)
#    Date:      !!actual-date!!
#    Copyright: !!userinfo-fullname!!, Chair Prof. Dillmann (HIS)
#               Institute for Anthropomatics (IFA)
#	        Karlsruhe Institute of Technology (KIT). All rights reserved
#	        http://his.anthropomatik.kit.edu

doc: 
	@doxygen

mrproper:
	@rm -rf *~ *.pyc

realclean: mrproper
	@rm -rf doc/

